{{- if .Values.ixConfig }}
apiVersion: v1
kind: ConfigMap
data:
  ix-config: |-
{{- with .Values.resourceName }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ixConfig }}
    {{- toYaml . | nindent 4 }}
{{- end }}

metadata:
  name: {{ .Values.cfgName }}
{{- end }}
